apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "rnk"
    operator: "Equal"
    value: "nr"
    effect: "NoSchedule"



