apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  containers:
  - name: nginx
    image: nginx
---














# apiVersion: v1
# kind: Pod
# metadata:
#   name: node-affinty
# spec:
#   affinity:
#     nodeAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#         nodeSelectorTerms:
#         - matchExpressions:
#           - key: rnk
#             operator: In
#             values:
#             - nr
#   containers:
#   - name: node-affinty
#     image: nginx