apiVersion: v1
kind: Pod
metadata:
  name: node-affinty
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: rnk
            operator: In
            values:
            - nr
  containers:
  - name: node-affinty
    image: nginx