apiVersion: v1
kind: Pod
metadata:
  name: node-affinty
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardwear
            operator: In
            values:
            - cpu
  containers:
  - name: node-affinty
    image: nginx