apiVersion: v1
kind: Pod
metadata:
  name: anti-affinity
  labels:
    purpose: "anti-affinity"
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: NotIn #anti-affinity
            values:
            - gpu
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "rnk"
    operator: "Equal"
    value: "naveen"
    effect: "NoExecute"